
services:
   selenium-firefox:
     image: 'selenium/standalone-firefox:latest'
     shm_size: '2g'
     privileged: true
     restart: always
     volumes:
       - /dev/shm:/dev/shm
     ports:
       - '4444:4444'
       - '7900:7900'