
spring:
  docker:
    compose:
      enabled: true
      file: selenium-standalone-chrome.yml

web-driver:
  browser: CHROME
  remote:
    enabled: true
    address: http://localhost:4444/wd/hub
    tracing-enabled: true